#!/usr/bin/env bats
# Tests for the data-driven client-ready report renderers (Markdown + RTF).
# The renderers are tested in isolation against a synthetic AUDIT_RESULTS array,
# so they are fully deterministic and need no sudo or real system state.

load test_helper

setup() {
	setup_raccoon_env
	# shellcheck source=/dev/null
	source "$SCRIPT_DIR/lib/audit/checks.sh"   # _check_explain, used by the report
	# shellcheck source=/dev/null
	source "$SCRIPT_DIR/lib/core/report.sh"
}

teardown() {
	teardown_raccoon_env
}

# Seed a representative result set. Mixes statuses, multiple categories, a check
# WITH a description (FileVault) and several WITHOUT one (Open Ports, ...).
_seed_results() {
	AUDIT_RESULTS=()
	AUDIT_RESULTS+=("pass"$'\t'"Core Security"$'\t'"FileVault: Enabled")
	AUDIT_RESULTS+=("fail"$'\t'"Core Security"$'\t'"Firewall: Disabled")
	AUDIT_RESULTS+=("warn"$'\t'"Network"$'\t'"Open Ports: 12 listening")
}

_set_branding() {
	REPORT_CLIENT="Jane Doe"
	REPORT_SHOP="MacFix Pro"
	REPORT_TECH="Mario Rossi"
	REPORT_MODEL="MacBook Pro"
	REPORT_MODEL_ID="MacBookPro18,3"
	REPORT_OS="14.5"
	REPORT_DATE="2026-06-24 15:00"
}

# --- Markdown, full branding -------------------------------------------------
@test "markdown report with all branding flags renders header, summary, checks" {
	_seed_results
	_set_branding
	run render_report_md
	assert_success
	assert_output_contains "# MacFix Pro — Security Audit Report"
	assert_output_contains "**Client:** Jane Doe"
	assert_output_contains "**Technician:** Mario Rossi"
	assert_output_contains "MacBook Pro (MacBookPro18,3)"
	assert_output_contains "**macOS:** 14.5"
	assert_output_contains "**Date:** 2026-06-24 15:00"
	assert_output_contains "## Summary"
	assert_output_contains "**3** checks"
	assert_output_contains "FileVault"
	assert_output_contains "Firewall"
	assert_output_contains "Open Ports"
	assert_output_contains "powered by Raccoon"
}

@test "markdown shows status symbols and known-check description" {
	_seed_results
	_set_branding
	run render_report_md
	assert_success
	assert_output_contains "✓ **FileVault**"
	assert_output_contains "✗ **Firewall**"
	# FileVault has a seeded plain-language description.
	assert_output_contains "Encrypts the whole disk"
}

# --- RTF, full branding ------------------------------------------------------
@test "rtf report with all branding flags is valid and branded" {
	_seed_results
	_set_branding
	run render_report_rtf
	assert_success
	# Valid RTF opens with the rtf1 control word and closes with a brace.
	[[ "$output" == '{\rtf1'* ]]
	[[ "$output" == *'}' ]]
	assert_output_contains "MacFix Pro - Security Audit Report"
	assert_output_contains "Client:} Jane Doe"
	assert_output_contains "Technician:} Mario Rossi"
	assert_output_contains '\par'
	assert_output_contains "powered by Raccoon"
}

# --- No branding -> Raccoon default fallback ---------------------------------
@test "markdown with no branding falls back to Raccoon header/footer" {
	_seed_results
	# No branding vars set at all.
	REPORT_CLIENT="" REPORT_SHOP="" REPORT_TECH=""
	REPORT_MODEL="" REPORT_MODEL_ID="" REPORT_OS="" REPORT_DATE=""
	run render_report_md
	assert_success
	assert_output_contains "# Raccoon — Security Audit Report"
	assert_output_contains "Generated by Raccoon"
	# Optional branding lines are omitted entirely.
	[[ "$output" != *"**Client:**"* ]]
	[[ "$output" != *"**Technician:**"* ]]
}

@test "rtf with no branding falls back to Raccoon header/footer" {
	_seed_results
	REPORT_CLIENT="" REPORT_SHOP="" REPORT_TECH=""
	REPORT_MODEL="" REPORT_MODEL_ID="" REPORT_OS="" REPORT_DATE=""
	run render_report_rtf
	assert_success
	[[ "$output" == '{\rtf1'* ]]
	assert_output_contains "Raccoon - Security Audit Report"
	[[ "$output" != *"Client:}"* ]]
}

# --- DECOUPLING: a brand-new synthetic check appears with ZERO renderer edits -
@test "an extra synthetic check appears in both reports without touching renderer code" {
	_seed_results
	# A check name that exists in NO audit function and NO description table.
	AUDIT_RESULTS+=("warn"$'\t'"Synthetic Category"$'\t'"Brand New Check: 42 widgets")

	run render_report_md
	assert_success
	assert_output_contains "## Synthetic Category"
	assert_output_contains "Brand New Check"
	assert_output_contains "42 widgets"
	# Count reflects the extra entry (3 seeded + 1 synthetic).
	assert_output_contains "**4** checks"

	run render_report_rtf
	assert_success
	assert_output_contains "Synthetic Category"
	assert_output_contains "Brand New Check"
	assert_output_contains "42 widgets"
}

# --- A check with no description entry still renders -------------------------
@test "a check lacking a plain-language entry renders its technical info" {
	AUDIT_RESULTS=()
	AUDIT_RESULTS+=("pass"$'\t'"Misc"$'\t'"Totally Undocumented Check: some value")
	run render_report_md
	assert_success
	assert_output_contains "Totally Undocumented Check"
	assert_output_contains "some value"
	# _check_explain returns nothing for unknown names.
	[[ "$(_check_explain "Totally Undocumented Check")" == "" ]]
}

# --- A check with an empty value renders the name only -----------------------
@test "a check with an empty value renders without breaking" {
	AUDIT_RESULTS=()
	AUDIT_RESULTS+=("pass"$'\t'"Misc"$'\t'"Bare Check")
	run render_report_md
	assert_success
	assert_output_contains "**Bare Check**"
}

# --- RTF escaping ------------------------------------------------------------
@test "rtf_escape escapes RTF delimiters" {
	run rtf_escape 'a{b}c\d'
	assert_success
	assert_output 'a\{b\}c\\d'
}

@test "rtf_escape converts accented characters to unicode + byte fallback" {
	run rtf_escape 'à'
	assert_success
	# U+00E0 = 224 decimal, 0xe0 byte fallback.
	assert_output "\\u224\\'e0"
}

@test "values with special characters survive into the RTF report" {
	AUDIT_RESULTS=()
	AUDIT_RESULTS+=("warn"$'\t'"Weird"$'\t'"Odd Value: braces {x} and slash here")
	run render_report_rtf
	assert_success
	assert_output_contains '\{x\}'
}

# --- Integration smoke: the audit CLI actually writes the files --------------
# Basic (non-deep) audit runs without sudo; checks still populate AUDIT_RESULTS.
@test "audit --md --report writes a Markdown file" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --md --report "$HOME/report.md"
	assert_success
	[[ -f "$HOME/report.md" ]]
	grep -q "Security Audit Report" "$HOME/report.md"
	grep -q "powered by Raccoon" "$HOME/report.md"
}

@test "audit --rtf --report writes a valid RTF file" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --rtf --report "$HOME/report.rtf" --shop "MacFix Pro"
	assert_success
	[[ -f "$HOME/report.rtf" ]]
	head -c 6 "$HOME/report.rtf" | grep -q '{\\rtf1'
	grep -q "MacFix Pro" "$HOME/report.rtf"
}

@test "audit --report client.md infers Markdown from the extension" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --report "$HOME/client.md"
	assert_success
	[[ -f "$HOME/client.md" ]]
	grep -q "Security Audit Report" "$HOME/client.md"
}

# --- Feature 1: --explain -----------------------------------------------------
@test "_check_explain returns a note for known checks and empty for unknown" {
	# shellcheck source=/dev/null
	source "$SCRIPT_DIR/lib/audit/checks.sh"
	[[ -n "$(_check_explain FileVault)" ]]
	[[ -n "$(_check_explain Firewall)" ]]
	# A check with no entry yields an empty string (no spurious explanation).
	[[ -z "$(_check_explain "No Such Check Name")" ]]
}

@test "audit --explain prints plain-language notes under issues (text)" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --explain
	assert_success
	assert_output_contains "->"
}

@test "audit --explain --json keeps the notes out of the JSON" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --explain --json
	assert_success
	# The machine-readable format must never carry the human notes.
	[[ "$output" != *"->"* ]]
}

# --- Feature 2: remediation report -------------------------------------------
@test "an audit run records individual check results in the history JSON" {
	run bash "$SCRIPT_DIR/bin/audit.sh"
	assert_success
	local hf
	hf="$(ls "$HOME/.raccoon/audit-history"/audit_*.json 2>/dev/null | head -1)"
	[[ -n "$hf" ]]
	# results array is now populated, not the old empty [].
	grep -q '"name":' "$hf"
	grep -q '"status":' "$hf"
}

@test "show_diff handles a previous run with individual results without crashing" {
	local hd="$HOME/.raccoon/audit-history"
	mkdir -p "$hd"
	# Pre-feature history: empty results array (backward-compat path).
	cat > "$hd/audit_2026-01-01_00:00:00.json" <<'JSON'
{
  "timestamp": "2026-01-01_00:00:00",
  "pass": 10,
  "warning": 5,
  "fail": 3,
  "deep": false,
  "results": []
}
JSON
	# Post-feature history: populated results.
	cat > "$hd/audit_2026-02-02_00:00:00.json" <<'JSON'
{
  "timestamp": "2026-02-02_00:00:00",
  "pass": 12,
  "warning": 4,
  "fail": 2,
  "deep": false,
  "results": [
    {"status": "fail", "category": "Core Security", "name": "Firewall", "value": "Disabled"}
  ]
}
JSON
	ln -sf "$hd/audit_2026-02-02_00:00:00.json" "$hd/latest.json"
	run bash "$SCRIPT_DIR/bin/audit.sh" --diff
	assert_success
	assert_output_contains "Previous:"
}

@test "audit --diff against an empty-results history still shows counters" {
	local hd="$HOME/.raccoon/audit-history"
	mkdir -p "$hd"
	cat > "$hd/audit_2026-01-01_00:00:00.json" <<'JSON'
{
  "timestamp": "2026-01-01_00:00:00",
  "pass": 10,
  "warning": 5,
  "fail": 3,
  "deep": false,
  "results": []
}
JSON
	ln -sf "$hd/audit_2026-01-01_00:00:00.json" "$hd/latest.json"
	run bash "$SCRIPT_DIR/bin/audit.sh" --diff
	assert_success
	assert_output_contains "Previous:"
}

@test "audit --remediation works without any history" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --remediation
	assert_success
	assert_output_contains "Intervention report"
	assert_output_contains "Issues found"
	assert_output_contains "Generated by Raccoon"
}

@test "audit --remediation --report writes the report to a file" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --remediation --report "$HOME/remediation.txt"
	assert_success
	[[ -f "$HOME/remediation.txt" ]]
	grep -q "Intervention report" "$HOME/remediation.txt"
}

# --- Feature 3.1: baseline ---------------------------------------------------
@test "audit --baseline writes a baseline.json with individual results" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --baseline
	assert_success
	[[ -f "$HOME/.raccoon/baseline.json" ]]
	grep -q '"name":' "$HOME/.raccoon/baseline.json"
	assert_output_contains "Baseline saved"
}

@test "audit --baseline-diff without a baseline explains and exits 0" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --baseline-diff
	assert_success
	assert_output_contains "No baseline found"
}

@test "audit --baseline-diff with a baseline shows the baseline comparison" {
	mkdir -p "$HOME/.raccoon"
	cat > "$HOME/.raccoon/baseline.json" <<'JSON'
{
  "timestamp": "2026-01-01_09:00:00",
  "pass": 10,
  "warning": 5,
  "fail": 3,
  "deep": false,
  "results": [
    {"status": "fail", "category": "Core Security", "name": "Firewall", "value": "Disabled"}
  ]
}
JSON
	run bash "$SCRIPT_DIR/bin/audit.sh" --baseline-diff
	assert_success
	assert_output_contains "Comparison with baseline"
}

@test "audit --baseline-reset without a baseline exits 0" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --baseline-reset
	assert_success
	assert_output_contains "No baseline to remove"
}

@test "audit --baseline-reset declined keeps the baseline file" {
	mkdir -p "$HOME/.raccoon"
	echo '{"timestamp":"x","results":[]}' > "$HOME/.raccoon/baseline.json"
	run bash "$SCRIPT_DIR/bin/audit.sh" --baseline-reset <<< "n"
	assert_success
	[[ -f "$HOME/.raccoon/baseline.json" ]]
}

# --- Feature 3.2: alerts / notifications -------------------------------------
@test "send_notification exits 0 when there are no issues" {
	# osascript may fail in CI; the function guards it with || true.
	run bash -c "source '$SCRIPT_DIR/bin/audit.sh'; PASS_count=5 WARN_count=0 FAIL_count=0; send_notification"
	assert_success
}

@test "audit --alert exits 0" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --alert
	assert_success
}

# --- Feature 3.5: schedule ---------------------------------------------------
@test "audit --schedule weekly creates the LaunchAgent plist" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --schedule weekly
	assert_success
	[[ -f "$HOME/Library/LaunchAgents/com.raccoon.audit.plist" ]]
	grep -q "<key>Weekday</key>" "$HOME/Library/LaunchAgents/com.raccoon.audit.plist"
}

@test "audit --schedule status with no schedule reports none" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --schedule status
	assert_success
	assert_output_contains "No active schedule"
}

@test "audit --schedule remove with no schedule exits 0" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --schedule remove
	assert_success
	assert_output_contains "Schedule removed"
}

@test "audit --watch still works (alias for --schedule weekly)" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --watch
	assert_success
	[[ -f "$HOME/Library/LaunchAgents/com.raccoon.audit.plist" ]]
}

@test "audit --schedule monthly sets a monthly interval" {
	run bash "$SCRIPT_DIR/bin/audit.sh" --schedule monthly
	assert_success
	grep -q "<key>Day</key>" "$HOME/Library/LaunchAgents/com.raccoon.audit.plist"
}
