#!/bin/bash
# Generate the Raycast integrations from `rcc --help`, which prints one
# "  rcc <cmd>:<description>" line per subcommand. Two outputs:
#
#   raycast/commands/*.sh            Raycast Script Commands (no build step)
#   raycast-extension/src/commands.ts Command table for the Store extension
#
# Everything runs inside Raycast. Subcommands that shell out to sudo are flagged
# so the UI can warn about the prompt, but they still run headless: rcc escalates
# through pam_tid, whose Touch ID dialog needs no controlling terminal.
#
# Usage: ./raycast/generate.sh   (re-run after adding a new rcc subcommand)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${REPO_DIR}/raycast/commands"
TS_OUT="${REPO_DIR}/raycast-extension/src/commands.ts"
RCC_FALLBACK="$(command -v rcc || echo "${REPO_DIR}/rcc")"

mkdir -p "$OUT_DIR" "$(dirname "$TS_OUT")"

# Subcommands that call sudo -> rcc will raise a Touch ID prompt.
needs_root() {
	local script="${REPO_DIR}/bin/${1}.sh"
	[[ -f "$script" ]] || return 1
	grep -qE '(^|[^_[:alnum:]])sudo ' "$script"
}

title_case() {
	printf '%s' "$1" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1'
}

json_escape() {
	printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

# `rcc --help` lists one subcommand per line, name and description in two
# space-aligned columns:
#
#   "  rcc audit deep     Security audit (full)"
#
# The name's own words are separated by a single space, the two columns by two
# or more, which is what tells them apart. Nothing else in the help is indented
# and starts with "rcc".
HELP_LINE='^[[:space:]]+rcc[[:space:]]+([a-z][a-z0-9-]*([[:space:]][a-z][a-z0-9-]*)*)[[:space:]][[:space:]]+([^[:space:]].*)$'

# Parse the whole help before touching the tree. An `rcc --help` this script
# cannot read used to mean an empty command list written over the real one; now
# it means no files are removed and no files are written.
all_args=()
all_descs=()
while IFS= read -r line; do
	line="${line%$'\r'}"
	[[ $line =~ $HELP_LINE ]] || continue
	all_args+=("${BASH_REMATCH[1]}")
	all_descs+=("${BASH_REMATCH[3]}")
done < <(NO_COLOR=1 "${REPO_DIR}/rcc" --help)

if [[ ${#all_args[@]} -eq 0 ]]; then
	echo "generate.sh: read no subcommands out of \`rcc --help\`." >&2
	echo "The help format changed; fix HELP_LINE before running this again." >&2
	echo "Nothing was deleted." >&2
	exit 1
fi

rm -f "$OUT_DIR"/rcc-*.sh

ts_entries=""
count=0

for index in "${!all_args[@]}"; do
	args="${all_args[$index]}"
	desc="${all_descs[$index]}"

	id="${args// /-}"
	title="$(title_case "$args")"
	file="${OUT_DIR}/rcc-${id}.sh"

	# Commands that never need root are pinned to RCC_NO_PROMPT so they can never
	# raise a Touch ID dialog. The privileged ones are left able to ask, once,
	# because running a Script Command is always a deliberate act.
	if needs_root "${args%% *}"; then
		root=true
		env_prefix="NO_COLOR=1"
	else
		root=false
		env_prefix="NO_COLOR=1 RCC_NO_PROMPT=1"
	fi

	# --- Script Command ---
	cat > "$file" <<EOF
#!/bin/bash

# @raycast.schemaVersion 1
# @raycast.title Raccoon ${title}
# @raycast.mode fullOutput
#
# Optional parameters:
# @raycast.icon 🦝
# @raycast.packageName Raccoon
#
# Documentation:
# @raycast.description ${desc}
# @raycast.author Eugenio Zamengo Pontrelli
# @raycast.authorURL https://github.com/thousandflowers/Raccoon

RCC="\$(command -v rcc || echo "${RCC_FALLBACK}")"
[[ -x "\$RCC" ]] || { echo "rcc not found — brew install thousandflowers/raccoon/rcc"; exit 1; }

${env_prefix} exec "\${RCC}" ${args}
EOF
	chmod +x "$file"

	# --- extension table row ---
	ts_args="$(printf '%s' "$args" | awk '{for(i=1;i<=NF;i++) printf "%s\"%s\"", (i>1?", ":""), $i}')"
	ts_entries+="  { id: \"${id}\", args: [${ts_args}], title: \"$(json_escape "$title")\", description: \"$(json_escape "$desc")\", needsRoot: ${root} },"$'\n'

	count=$((count + 1))
done

cat > "$TS_OUT" <<EOF
// GENERATED by raycast/generate.sh from \`rcc --help\` — do not edit by hand.

export type RccCommand = {
  /** Slug, e.g. "audit-deep". */
  id: string;
  /** Argv passed to rcc, e.g. ["audit", "deep"]. */
  args: string[];
  title: string;
  description: string;
  /** Calls sudo, so rcc will raise a Touch ID prompt. Still runs inside Raycast. */
  needsRoot: boolean;
};

export const COMMANDS: RccCommand[] = [
${ts_entries}];

export function findCommand(id: string): RccCommand {
  const found = COMMANDS.find((c) => c.id === id);
  if (!found) throw new Error(\`Unknown rcc command: \${id}\`);
  return found;
}
EOF

# Keep the generated TS in the format `ray lint` expects.
if [[ -x "${REPO_DIR}/raycast-extension/node_modules/.bin/prettier" ]]; then
	"${REPO_DIR}/raycast-extension/node_modules/.bin/prettier" --write "$TS_OUT" > /dev/null
fi

echo "Generated ${count} script commands in ${OUT_DIR}"
echo "Generated ${count} extension entries in ${TS_OUT}"
