#!/bin/bash
# Generate the Raycast integrations from `rcc --help`, which prints one
# "  rcc <cmd>:<description>" line per subcommand. Two outputs:
#
#   raycast/commands/*.sh            Raycast Script Commands (no build step)
#   raycast-extension/src/commands.ts Command table for the Store extension
#
# Everything runs inside Raycast. Subcommands that shell out to sudo are flagged
# so the UI can warn about the prompt, but they still run headless: rcc escalates
# through pam_tid, whose Touch ID dialog needs no controlling terminal.
#
# Usage: ./raycast/generate.sh   (re-run after adding a new rcc subcommand)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${REPO_DIR}/raycast/commands"
TS_OUT="${REPO_DIR}/raycast-extension/src/commands.ts"
RCC_FALLBACK="$(command -v rcc || echo "${REPO_DIR}/rcc")"

mkdir -p "$OUT_DIR" "$(dirname "$TS_OUT")"
rm -f "$OUT_DIR"/rcc-*.sh

# Subcommands that call sudo -> rcc will raise a Touch ID prompt.
needs_root() {
	local script="${REPO_DIR}/bin/${1}.sh"
	[[ -f "$script" ]] || return 1
	grep -qE '(^|[^_[:alnum:]])sudo ' "$script"
}

title_case() {
	printf '%s' "$1" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1'
}

json_escape() {
	printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

ts_entries=""
count=0

while IFS= read -r line; do
	# "  rcc audit deep:Security audit (full)" -> args="audit deep", desc="Security audit (full)"
	args="${line%%:*}"; args="${args##*rcc }"
	desc="${line#*:}"
	[[ -n "$args" && -n "$desc" ]] || continue

	id="${args// /-}"
	title="$(title_case "$args")"
	file="${OUT_DIR}/rcc-${id}.sh"

	# Commands that never need root are pinned to RCC_NO_PROMPT so they can never
	# raise a Touch ID dialog. The privileged ones are left able to ask, once,
	# because running a Script Command is always a deliberate act.
	if needs_root "${args%% *}"; then
		root=true
		env_prefix="NO_COLOR=1"
	else
		root=false
		env_prefix="NO_COLOR=1 RCC_NO_PROMPT=1"
	fi

	# --- Script Command ---
	cat > "$file" <<EOF
#!/bin/bash

# @raycast.schemaVersion 1
# @raycast.title Raccoon ${title}
# @raycast.mode fullOutput
#
# Optional parameters:
# @raycast.icon 🦝
# @raycast.packageName Raccoon
#
# Documentation:
# @raycast.description ${desc}
# @raycast.author Eugenio Zamengo Pontrelli
# @raycast.authorURL https://github.com/thousandflowers/Raccoon

RCC="\$(command -v rcc || echo "${RCC_FALLBACK}")"
[[ -x "\$RCC" ]] || { echo "rcc not found — brew install thousandflowers/raccoon/rcc"; exit 1; }

${env_prefix} exec "\${RCC}" ${args}
EOF
	chmod +x "$file"

	# --- extension table row ---
	ts_args="$(printf '%s' "$args" | awk '{for(i=1;i<=NF;i++) printf "%s\"%s\"", (i>1?", ":""), $i}')"
	ts_entries+="  { id: \"${id}\", args: [${ts_args}], title: \"$(json_escape "$title")\", description: \"$(json_escape "$desc")\", needsRoot: ${root} },"$'\n'

	count=$((count + 1))
done < <(NO_COLOR=1 "${REPO_DIR}/rcc" --help | grep -E '^\s+rcc .+:')

cat > "$TS_OUT" <<EOF
// GENERATED by raycast/generate.sh from \`rcc --help\` — do not edit by hand.

export type RccCommand = {
  /** Slug, e.g. "audit-deep". */
  id: string;
  /** Argv passed to rcc, e.g. ["audit", "deep"]. */
  args: string[];
  title: string;
  description: string;
  /** Calls sudo, so rcc will raise a Touch ID prompt. Still runs inside Raycast. */
  needsRoot: boolean;
};

export const COMMANDS: RccCommand[] = [
${ts_entries}];

export function findCommand(id: string): RccCommand {
  const found = COMMANDS.find((c) => c.id === id);
  if (!found) throw new Error(\`Unknown rcc command: \${id}\`);
  return found;
}
EOF

# Keep the generated TS in the format `ray lint` expects.
if [[ -x "${REPO_DIR}/raycast-extension/node_modules/.bin/prettier" ]]; then
	"${REPO_DIR}/raycast-extension/node_modules/.bin/prettier" --write "$TS_OUT" > /dev/null
fi

echo "Generated ${count} script commands in ${OUT_DIR}"
echo "Generated ${count} extension entries in ${TS_OUT}"
